/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
union _obf_2_SECRET_$node ;
enum _obf_2_SECRET_$op ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
char **_global_obfenvp  =    (char **)0;
extern int pthread_cond_broadcast(int *cond ) ;
void _obf_4_bf_7(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_6(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
char const   *_obf_2_SECRET_$strings  =    "";
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
void _obf_4_bf_4(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
extern int printf(char const   * __restrict  __format  , ...) ;
typedef unsigned long __uint64_t;
typedef __uint64_t uint64_t;
uint64_t SECRET(unsigned long input ) ;
extern int pthread_cond_signal(int *cond ) ;
union _obf_2_SECRET_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern int raise(int sig ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int scanf(char const   *format  , ...) ;
extern int unlink(char const   *filename ) ;
void _obf_4_bf_5(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
char **_global_obfargv  =    (char **)0;
unsigned long _obf_6_entropy  =    1042652047046269365UL;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern  __attribute__((__nothrow__)) unsigned long ( __attribute__((__nonnull__(1),
__leaf__)) strtoul)(char const   * __restrict  __nptr , char ** __restrict  __endptr ,
                    int __base ) ;
extern void abort() ;
void _obf_7_stringEncoder(int n , char str[] ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
int main(int argc , char **argv , char **_formal_obfenvp ) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
enum _obf_2_SECRET_$op {
    _obf_2_SECRET__constant_int$result_STA_0$value_LIT_0 = 13,
    _obf_2_SECRET__formal$result_STA_0$value_LIT_0 = 213,
    _obf_2_SECRET__goto$label_LAB_0 = 56,
    _obf_2_SECRET__return_unsigned_long$expr_STA_0 = 50,
    _obf_2_SECRET__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1 = 11,
    _obf_2_SECRET__load_int$left_STA_0$result_STA_0 = 22,
    _obf_2_SECRET__global$result_STA_0$value_LIT_0 = 138,
    _obf_2_SECRET__constant_unsigned_long$result_STA_0$value_LIT_0 = 125,
    _obf_2_SECRET__load_unsigned_long$left_STA_0$result_STA_0 = 146,
    _obf_2_SECRET__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 137,
    _obf_2_SECRET__convert_int2unsigned_long$left_STA_0$result_STA_0 = 217,
    _obf_2_SECRET__store_int$left_STA_0$right_STA_1 = 201,
    _obf_2_SECRET__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 = 187,
    _obf_2_SECRET__constant_void_star$result_STA_0$value_LIT_0 = 172,
    _obf_2_SECRET__store_unsigned_long$left_STA_0$right_STA_1 = 74,
    _obf_2_SECRET__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1 = 38,
    _obf_2_SECRET__local$result_STA_0$value_LIT_0 = 96
} ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
void _obf_4_bf_3(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
unsigned char _obf_2_SECRET_$array[1][110]  = { {        _obf_2_SECRET__global$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _obf_2_SECRET__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _obf_2_SECRET__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _obf_2_SECRET__formal$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _obf_2_SECRET__load_unsigned_long$left_STA_0$result_STA_0,        _obf_2_SECRET__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1,        _obf_2_SECRET__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _obf_2_SECRET__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _obf_2_SECRET__load_int$left_STA_0$result_STA_0,        _obf_2_SECRET__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _obf_2_SECRET__store_int$left_STA_0$right_STA_1,        _obf_2_SECRET__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _obf_2_SECRET__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _obf_2_SECRET__load_int$left_STA_0$result_STA_0,        _obf_2_SECRET__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _obf_2_SECRET__local$result_STA_0$value_LIT_0, 
            (unsigned char)12,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _obf_2_SECRET__store_int$left_STA_0$right_STA_1,        _obf_2_SECRET__global$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _obf_2_SECRET__constant_void_star$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _obf_2_SECRET__constant_unsigned_long$result_STA_0$value_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _obf_2_SECRET__local$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _obf_2_SECRET__load_int$left_STA_0$result_STA_0,        _obf_2_SECRET__convert_int2unsigned_long$left_STA_0$result_STA_0,        _obf_2_SECRET__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1, 
            _obf_2_SECRET__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1,        _obf_2_SECRET__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1,        _obf_2_SECRET__load_int$left_STA_0$result_STA_0,        _obf_2_SECRET__convert_int2unsigned_long$left_STA_0$result_STA_0, 
            _obf_2_SECRET__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _obf_2_SECRET__store_unsigned_long$left_STA_0$right_STA_1,        _obf_2_SECRET__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _obf_2_SECRET__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _obf_2_SECRET__load_unsigned_long$left_STA_0$result_STA_0,        _obf_2_SECRET__return_unsigned_long$expr_STA_0}};
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
void _obf_4_bf_8(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
int _global_obfargc  =    0;
void obfmegaInit(void) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
void obfindirect_array_i$nit(void) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
void _obf_4_bf_1(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
void _obf_4_bf_10(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
int indirect_array[10] ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
unsigned long _obf_6_alwaysZero  =    0;
extern double sqrt(double x ) ;
void _obf_4_bf_9(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
extern void *malloc(unsigned int size ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
void _obf_4_bf_2(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void _obf_4_bf_2(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_2(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
uint64_t SECRET(unsigned long input ) 
{ 
  int _obf_1__BARRIER_1 ;
  int _obf_1__BARRIER_2 ;
  char _obf_2_SECRET_$locals[24] ;
  union _obf_2_SECRET_$node _obf_2_SECRET_$stack[1][32] ;
  union _obf_2_SECRET_$node *_obf_2_SECRET_$sp[1] ;
  unsigned char *_obf_2_SECRET_$pc[1] ;
  unsigned char _obf_2_SECRET_$currentOp ;

  {
  _obf_1__BARRIER_1 = 1;
  _obf_1__BARRIER_2 = 1;
  _obf_2_SECRET_$sp[0] = _obf_2_SECRET_$stack[0];
  _obf_2_SECRET_$pc[0] = _obf_2_SECRET_$array[0];
  while (1) {
    _obf_2_SECRET_$currentOp = *(_obf_2_SECRET_$pc[0]);
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__store_unsigned_long$left_STA_0$right_STA_1) + ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__store_unsigned_long$left_STA_0$right_STA_1) >> (signed char)7)) ^ ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__store_unsigned_long$left_STA_0$right_STA_1) >> (signed char)7)) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      *((unsigned long *)(_obf_2_SECRET_$sp[0] + 0)->_void_star) = (_obf_2_SECRET_$sp[0] + -1)->_unsigned_long;
      _obf_2_SECRET_$sp[0] += -2;
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1) + ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1) >> (signed char)7)) ^ ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusPI_void_star_unsigned_long2void_star$left_STA_0$result_STA_0$right_STA_1) >> (signed char)7)) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + -1)->_void_star = (_obf_2_SECRET_$sp[0] + 0)->_void_star + (_obf_2_SECRET_$sp[0] + -1)->_unsigned_long;
      (_obf_2_SECRET_$sp[0]) --;
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__load_int$left_STA_0$result_STA_0) + ((unsigned char)1 << 7)) + ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__load_int$left_STA_0$result_STA_0) + ((unsigned char)1 << 7)) >> (signed char)7)) ^ ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__load_int$left_STA_0$result_STA_0) + ((unsigned char)1 << 7)) >> (signed char)7)) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + 0)->_int = *((int *)(_obf_2_SECRET_$sp[0] + 0)->_void_star);
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__goto$label_LAB_0) + ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__goto$label_LAB_0) >> (signed char)7)) ^ ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__goto$label_LAB_0) >> (signed char)7)) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      _obf_2_SECRET_$pc[0] += *((int *)_obf_2_SECRET_$pc[0]);
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__return_unsigned_long$expr_STA_0) + ((unsigned char)1 << 7)) ^ ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__return_unsigned_long$expr_STA_0) + ((unsigned char)1 << 7)) >> (signed char)7)) - ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__return_unsigned_long$expr_STA_0) + ((unsigned char)1 << 7)) >> (signed char)7)) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      return ((_obf_2_SECRET_$sp[0] + 0)->_unsigned_long);
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1) + ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1) >> (signed char)7)) ^ ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1) >> (signed char)7)) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + -1)->_int = ((_obf_2_SECRET_$sp[0] + 0)->_int ^ (_obf_2_SECRET_$sp[0] + -1)->_int) + (((_obf_2_SECRET_$sp[0] + 0)->_int & (_obf_2_SECRET_$sp[0] + -1)->_int) + ((_obf_2_SECRET_$sp[0] + 0)->_int & (_obf_2_SECRET_$sp[0] + -1)->_int));
      (_obf_2_SECRET_$sp[0]) --;
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__formal$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) + ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__formal$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) >> (signed char)7)) ^ ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__formal$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) >> (signed char)7)) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      switch (*((int *)_obf_2_SECRET_$pc[0])) {
      case 0: 
      (_obf_2_SECRET_$sp[0] + 1)->_void_star = (void *)(& input);
      break;
      }
      (_obf_2_SECRET_$sp[0]) ++;
      _obf_2_SECRET_$pc[0] += 4;
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__store_int$left_STA_0$right_STA_1) + ((unsigned char)1 << 7)) + ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__store_int$left_STA_0$right_STA_1) + ((unsigned char)1 << 7)) >> (signed char)7)) ^ ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__store_int$left_STA_0$right_STA_1) + ((unsigned char)1 << 7)) >> (signed char)7)) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      *((int *)(_obf_2_SECRET_$sp[0] + 0)->_void_star) = (_obf_2_SECRET_$sp[0] + -1)->_int;
      _obf_2_SECRET_$sp[0] += -2;
    } else
    if (((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__convert_int2unsigned_long$left_STA_0$result_STA_0) + ((unsigned char)1 << 7)) - ((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__convert_int2unsigned_long$left_STA_0$result_STA_0) + ((unsigned char)1 << 7)) << (unsigned char)1) & ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__convert_int2unsigned_long$left_STA_0$result_STA_0) + ((unsigned char)1 << 7)) >> (signed char)7))) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + 0)->_unsigned_long = (unsigned long )(_obf_2_SECRET_$sp[0] + 0)->_int;
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_void_star$result_STA_0$value_LIT_0) + ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_void_star$result_STA_0$value_LIT_0) >> (signed char)7)) ^ ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_void_star$result_STA_0$value_LIT_0) >> (signed char)7)) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + 1)->_void_star = *((void **)_obf_2_SECRET_$pc[0]);
      (_obf_2_SECRET_$sp[0]) ++;
      _obf_2_SECRET_$pc[0] += 8;
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_int$result_STA_0$value_LIT_0) ^ ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_int$result_STA_0$value_LIT_0) >> (signed char)7)) - ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_int$result_STA_0$value_LIT_0) >> (signed char)7)) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + 1)->_int = *((int *)_obf_2_SECRET_$pc[0]);
      (_obf_2_SECRET_$sp[0]) ++;
      _obf_2_SECRET_$pc[0] += 4;
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1) + ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1) >> (signed char)7)) ^ ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__PlusPI_void_star_int2void_star$right_STA_0$result_STA_0$left_STA_1) >> (signed char)7)) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + -1)->_void_star = (_obf_2_SECRET_$sp[0] + -1)->_void_star + (_obf_2_SECRET_$sp[0] + 0)->_int;
      (_obf_2_SECRET_$sp[0]) --;
    } else
    if (((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__global$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) - ((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__global$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) << (unsigned char)1) & ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__global$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) >> (signed char)7))) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      switch (*((int *)_obf_2_SECRET_$pc[0])) {
      case 0: 
      (_obf_2_SECRET_$sp[0] + 1)->_void_star = (void *)(indirect_array);
      break;
      }
      (_obf_2_SECRET_$sp[0]) ++;
      _obf_2_SECRET_$pc[0] += 4;
    } else
    if (((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_unsigned_long$result_STA_0$value_LIT_0) - (((_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_unsigned_long$result_STA_0$value_LIT_0) + (_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_unsigned_long$result_STA_0$value_LIT_0)) & ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__constant_unsigned_long$result_STA_0$value_LIT_0) >> (signed char)7))) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_obf_2_SECRET_$pc[0]);
      (_obf_2_SECRET_$sp[0]) ++;
      _obf_2_SECRET_$pc[0] += 8;
    } else
    if (((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__load_unsigned_long$left_STA_0$result_STA_0) - (((_obf_2_SECRET_$currentOp - _obf_2_SECRET__load_unsigned_long$left_STA_0$result_STA_0) + (_obf_2_SECRET_$currentOp - _obf_2_SECRET__load_unsigned_long$left_STA_0$result_STA_0)) & ((signed char )(_obf_2_SECRET_$currentOp - _obf_2_SECRET__load_unsigned_long$left_STA_0$result_STA_0) >> (signed char)7))) - (unsigned char)1) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + 0)->_unsigned_long = *((unsigned long *)(_obf_2_SECRET_$sp[0] + 0)->_void_star);
    } else
    if ((((((_obf_2_SECRET_$currentOp - _obf_2_SECRET__local$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) ^ ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__local$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) >> (signed char)7)) - ((signed char )((_obf_2_SECRET_$currentOp - _obf_2_SECRET__local$result_STA_0$value_LIT_0) + ((unsigned char)1 << 7)) >> (signed char)7)) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + 1)->_void_star = (void *)(_obf_2_SECRET_$locals + *((int *)_obf_2_SECRET_$pc[0]));
      (_obf_2_SECRET_$sp[0]) ++;
      _obf_2_SECRET_$pc[0] += 4;
    } else
    if ((~ ((_obf_2_SECRET_$currentOp - _obf_2_SECRET__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1) | (_obf_2_SECRET__Mult_unsigned_long_unsigned_long2unsigned_long$left_STA_0$result_STA_0$right_STA_1 - _obf_2_SECRET_$currentOp)) >> (unsigned char)7) & (unsigned char)1) {
      (_obf_2_SECRET_$pc[0]) ++;
      (_obf_2_SECRET_$sp[0] + -1)->_unsigned_long = ((_obf_2_SECRET_$sp[0] + 0)->_unsigned_long & (_obf_2_SECRET_$sp[0] + -1)->_unsigned_long) * ((_obf_2_SECRET_$sp[0] + 0)->_unsigned_long | (_obf_2_SECRET_$sp[0] + -1)->_unsigned_long) + ((_obf_2_SECRET_$sp[0] + 0)->_unsigned_long & ~ (_obf_2_SECRET_$sp[0] + -1)->_unsigned_long) * (~ (_obf_2_SECRET_$sp[0] + 0)->_unsigned_long & (_obf_2_SECRET_$sp[0] + -1)->_unsigned_long);
      (_obf_2_SECRET_$sp[0]) --;
    } else {

    }
  }
}
}
int main(int argc , char **argv , char **_formal_obfenvp ) 
{ 
  unsigned long input ;
  unsigned long tmp ;
  uint64_t output ;
  uint64_t tmp___0 ;
  int obf_BARRIER_0 ;

  {
  obfmegaInit();
  _global_obfargc = argc;
  _global_obfargv = argv;
  _global_obfenvp = _formal_obfenvp;
  obf_BARRIER_0 = 1;
  if (argc < 2) {
    printf((char const   */* __restrict  */)"Call this program with 1 argument\n");
    return (1);
  }
  tmp = strtoul((char const   */* __restrict  */)*(argv + 1), (char **/* __restrict  */)0,
                10);
  input = tmp;
  tmp___0 = SECRET(input);
  output = tmp___0;
  printf((char const   */* __restrict  */)"%llu\n", output);
  return (0);
}
}
void _obf_4_bf_1(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_1(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void _obf_4_bf_8(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_8(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void obfindirect_array_i$nit(void) 
{ 


  {
  indirect_array[0] = 5;
  indirect_array[1] = 4;
  indirect_array[2] = 3;
  indirect_array[3] = 5;
  indirect_array[4] = 4;
  indirect_array[5] = 1;
  indirect_array[6] = 2;
  indirect_array[7] = 4;
  indirect_array[8] = 5;
  indirect_array[9] = 3;
}
}
void _obf_4_bf_5(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_5(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void _obf_4_bf_7(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_7(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void _obf_4_bf_4(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_4(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void _obf_7_stringEncoder(int n , char str[] ) 
{ 
  int encodeStrings_i3 ;

  {
  encodeStrings_i3 = 0;
  switch (n) {

  }
}
}
void obfmegaInit(void) 
{ 


  {
  obfindirect_array_i$nit();
}
}
void _obf_4_bf_6(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_6(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void _obf_4_bf_9(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_9(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void _obf_4_bf_10(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_10(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
void _obf_4_bf_3(unsigned long offset )  __attribute__((__optimize__(0), __optimize__("-fno-omit-frame-pointer"),
__noinline__)) ;
void _obf_4_bf_3(unsigned long offset ) 
{ 


  {
  __asm__  volatile   ("movq  %0, 8(%%rbp)": : "r" (offset));
}
}
